using CFCCoimbatore.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CFCCoimbatore.Utils
{

    public class BookUtil
    {
        public List<BookDetails> GetEnglishBooks()
        {
            List<BookDetails> books = new List<BookDetails>();

            books.Add(new BookDetails() { Title = "Proverbs Verse-By-Verse", Description = "Proverbs Verse-By-Verse", ImageName = "the-way-of-wisdom.jpg", ImageUrl = "../../Images/Books/", DetailsPageUrl = "https://www.cfcindia.com/books/proverbs-versebyverse" });
            books.Add(new BookDetails() { Title = "The Congregation The Club And The Church", Description = "To understand the difference between a congreation and a club and a church, read this book.", ImageName = "The-Congregation-The-Club-And-The-Church.jpg", ImageUrl = "../../Images/Books/", DetailsPageUrl = "https://www.cfcindia.com/books/the-congregation-the-club-and-the-church" });
            books.Add(new BookDetails() { Title = "The Spirit Filled Life", Description = "It is an immense privilege under the New Covenant to be filled with God’s Holy Spirit, every day. Yet the vast majority of Christians do not live this Spirit-filled life. What is the reason for this lack? Read on.", ImageName = "the_spirit_filled_life.jpg", ImageUrl = "../../Images/Books/", DetailsPageUrl = "https://www.cfcindia.com/books/the-spirit-filled-life" });
            books.Add(new BookDetails() { Title = "God's Work Done In God's Way", Description = "Is it possible to do God’s work today in the same way as it was done by Jesus and the apostles? The answer is YES. In this book Zac Poonen writes how he and his coworkers have proved that.", ImageName = "gods-work-done-in-gods-way.jpg", ImageUrl = "../../Images/Books/", DetailsPageUrl = "https://www.cfcindia.com/books/gods-work-done-in-gods-way" });
            books.Add(new BookDetails() { Title = "Hear! O My Sons", Description = "Fathers are told to bring up children “in the instruction of the Lord”. What I wrote in this book was instruction to my children from the Word of God to lead them to be devoted to the Lord Jesus.", ImageName = "hear-o-my-sons.jpg", ImageUrl = "../../Images/Books/", DetailsPageUrl = "https://www.cfcindia.com/books/hear-o-my-sons" });
            books.Add(new BookDetails() { Title = "Through The Bible", Description = "This commentary on all 66 books of the Bible indicates that every single book of the Bible has a message for us today.", ImageName = "through-the-bible.jpg", ImageUrl = "../../Images/Books/", DetailsPageUrl = "https://www.cfcindia.com/books/through-the-bible" });
            books.Add(new BookDetails() { Title = "Encouragement For Mothers", Description = "God is our heavenly Father who is interested in helping us to be a better parent and a better wife. Read and be encouraged by the truths that helped Annie Poonen in building a Godly home.", ImageName = "encouragement-for-mothers.jpg", ImageUrl = "../../Images/Books/", DetailsPageUrl = "https://www.cfcindia.com/books/encouragement-for-mothers" });
            books.Add(new BookDetails() { Title = "God Speaks Through Animals", Description = "Animals often speak to us through their behaviour and actions and thus point us to our common Creator. Like God used the donkey to help Balaam see a heavenly reality, we too can learn.", ImageName = "god-speaks-through-animals.jpg", ImageUrl = "../../Images/Books/", DetailsPageUrl = "https://www.cfcindia.com/books/god-speaks-through-animals" });
            books.Add(new BookDetails() { Title = "A Girl's Viewpoint", Description = "This is the story of a young girl's experiences...", ImageName = "a-girls-viewpoint.jpg", ImageUrl = "../../Images/Books/", DetailsPageUrl = "https://www.cfcindia.com/books/a-girls-viewpoint" });
            books.Add(new BookDetails() { Title = "A Good Foundation", Description = "A Guide to lay a good and strong foundation before you start your life journey, foundation which will not be shaken in storms and rain.", ImageName = "a-good-foundation.jpg", ImageUrl = "../../Images/Books/", DetailsPageUrl = "https://www.cfcindia.com/books/a-good-foundation" });
            books.Add(new BookDetails() { Title = "A Heavenly Home", Description = "Guide to the young married couples.", ImageName = "a-heavenly-home.jpg", ImageUrl = "../../Images/Books/", DetailsPageUrl = "https://www.cfcindia.com/books/a-heavenly-home" });
            books.Add(new BookDetails() { Title = "A Spiritual Leader", Description = @"Be challenged to become a spiritual leader who is an exemplary servant of Christ, and a role-model to the younger generation, one who says, “ Follow me as I follow Christ”?", ImageName = "a-spiritual-leader.jpg", ImageUrl = "../../Images/Books/", DetailsPageUrl = "https://www.cfcindia.com/books/a-spiritual-leader" });
            books.Add(new BookDetails() { Title = "Beauty For Ashes", Description = "Christ offers us the beauty of His own life to replace the ashes of our self-centered life. Read about how you can enjoy that privilege!", ImageName = "beauty-for-ashes.jpg", ImageUrl = "../../Images/Books/", DetailsPageUrl = "https://www.cfcindia.com/books/beauty-for-ashes" });
            books.Add(new BookDetails() { Title = "Fifty Marks Of Pharisees", Description = "God gives us his word to see more clearly the Pharaseeism within ourselves, not in others, be cleansed from it and become a useful vessel for His work.", ImageName = "fifty-marks-of-pharisees.jpg", ImageUrl = "../../Images/Books/", DetailsPageUrl = "https://www.cfcindia.com/books/fifty-marks-of-pharisees" });
            books.Add(new BookDetails() { Title = "Finding God's Will", Description = "How to find the will of God in various matters.", ImageName = "finding-gods-will.jpg", ImageUrl = "../../Images/Books/", DetailsPageUrl = "https://www.cfcindia.com/books/finding-gods-will" });
            books.Add(new BookDetails() { Title = "Gaining God's Approval", Description = "One day it will become evident that the honour and material gain were only a means by which God tested our hearts to see if we love Him above all else and we will see that the wisest people on earth are those who have sought with all their hearts to walk as Jesus walked . The greatest honour anyone can have is a place in the Bride of Christ as one who has been tested and approved by GOD Himself.", ImageName = "gaining-gods-approval.jpg", ImageUrl = "../../Images/Books/", DetailsPageUrl = "https://www.cfcindia.com/books/gaining-gods-approval" });
            books.Add(new BookDetails() { Title = "God Centred Praying", Description = "How we should pray.", ImageName = "god-centred-praying.jpg", ImageUrl = "../../Images/Books/", DetailsPageUrl = "https://www.cfcindia.com/books/god-centred-praying" });
            books.Add(new BookDetails() { Title = "God Made Mothers", Description = "A book for mothers...", ImageName = "god-made-mothers.jpg", ImageUrl = "../../Images/Books/", DetailsPageUrl = "https://www.cfcindia.com/books/god-made-mothers" });
            books.Add(new BookDetails() { Title = "Know Your Enemy", Description = "Young people, do you know you are the target of Satan's attacks? He seeks to pollute you with impurity, selfish ambition, pride, hypocrisy. But remember Satan was defeated on Calvary by our Lord Jesus. Our calling now is to register that tremendous victory over the forces of darkness everywhere we go.", ImageName = "know-your-enemy.jpg", ImageUrl = "../../Images/Books/", DetailsPageUrl = "https://www.cfcindia.com/books/know-your-enemy" });
            books.Add(new BookDetails() { Title = "Knowing God's Ways", Description = "Are you more awestruck by God's miraculous acts than with knowing Him and understanding His ways? Eternal life is not about living forever but knowing God and Christ Jesus whom He sent.", ImageName = "knowing-gods-ways.jpg", ImageUrl = "../../Images/Books/", DetailsPageUrl = "https://www.cfcindia.com/books/knowing-gods-ways" });
            books.Add(new BookDetails() { Title = "Living As Jesus Lived", Description = "Jesus is not only our Saviour but also our Forerunner (Heb. 6:20). He is our example of how to live at all times and in all situations, in the Spirit, in perfect obedience to God. He never acted on His own initiative, through His own abilities or for His own glory. He did only that which originated in God, by God's power and for God's glory.", ImageName = "living-as-jesus-lived.jpg", ImageUrl = "../../Images/Books/", DetailsPageUrl = "https://www.cfcindia.com/books/living-as-jesus-lived" });
            books.Add(new BookDetails() { Title = "Needed-Men Of God", Description = "How to become a man of God.", ImageName = "needed-men-of-god.jpg", ImageUrl = "../../Images/Books/", DetailsPageUrl = "https://www.cfcindia.com/books/neededmen-of-god" });
            books.Add(new BookDetails() { Title = "New Wine In New Wineskins", Description = "The traditions of men that have accumulated in Christendom through twenty centuries. If we are to fulfil God's purpose in our day and age, we must be willing to do violence to every tradition of man that is contrary to God's Word (Matt. 11:12). If you have the courage to do that, read this book. It will change your life and your ministry.", ImageName = "new-wine-in-new-wineskins.jpg", ImageUrl = "../../Images/Books/", DetailsPageUrl = "https://www.cfcindia.com/books/new-wine-in-new-wineskins" });
            books.Add(new BookDetails() { Title = "One Body In Christ", Description = "The Church is called to manifest the beauty of Christ’s Love to the world which is a fundamental necessity for the spread of the gospel. Many churches are instead hot-beds of internal politics and rivalry. What can we do to rectify the dismal state of interpersonal relationships in the Christian community today? The Word of God has an answer if we care to listen…", ImageName = "one-body-in-christ.jpg", ImageUrl = "../../Images/Books/", DetailsPageUrl = "https://www.cfcindia.com/books/one-body-in-christ" });
            books.Add(new BookDetails() { Title = "Practical Discipleship", Description = "When Jesus preached discipleship to the multitudes, they dwindled down to a handful of disciples. But it was through these faithful few that Jesus accomplished His purposes in the world. Now, He calls you to the same ministry.", ImageName = "practical-discipleship.jpg", ImageUrl = "../../Images/Books/", DetailsPageUrl = "https://www.cfcindia.com/books/practical-discipleship" });
            books.Add(new BookDetails() { Title = "Principles Of Serving God", Description = "God needs uncompromising men today who will stand before His face and hear His voice daily, men whose only desire is God Himself.", ImageName = "principles-of-serving-god.jpg", ImageUrl = "../../Images/Books/", DetailsPageUrl = "https://www.cfcindia.com/books/principles-of-serving-god" });
            books.Add(new BookDetails() { Title = "Secrets Of Victory", Description = "Do you believe that God loves you as much as He loves Jesus if you are a disciple of Jesus? Find your security in this love. Believe with all your heart that God wants to help you to live in victory at all times.", ImageName = "secrets-of-victory.jpg", ImageUrl = "../../Images/Books/", DetailsPageUrl = "https://www.cfcindia.com/books/secrets-of-victory" });
            books.Add(new BookDetails() { Title = "Sex, Love & Marriage", Description = "Is it alright to date someone? What about falling in love? How should I choose my life partner? Find, in this book, some clear advice to help you through your teen and youth years.", ImageName = "sex-love-marriage.jpg", ImageUrl = "../../Images/Books/", DetailsPageUrl = "https://www.cfcindia.com/books/sex-love-marriage" });
            books.Add(new BookDetails() { Title = "The Day Of Small Beginnings", Description = "This book , a much needed spiritual challenge for any man or woman who longs to be used by God. Read some of the important lessons that Zac Poonen and his co workers learned as they sought to serve the Lord, building His church. Just as large doors swing on small hinges they learned that small decisions determined the quality of their work for the Lord.", ImageName = "the-day-of-small-beginnings.jpg", ImageUrl = "../../Images/Books/", DetailsPageUrl = "https://www.cfcindia.com/books/the-day-of-small-beginnings" });
            books.Add(new BookDetails() { Title = "The Final Triumph", Description = "Verse by verse through Revelation.", ImageName = "the-final-triumph.jpg", ImageUrl = "../../Images/Books/", DetailsPageUrl = "https://www.cfcindia.com/books/the-final-triumph" });
            books.Add(new BookDetails() { Title = "The Full Gospel", Description = "Jesus said if we knew the truth, the truth would set us free ( John 8:32) The proof that we have really heard the truth is that we are freed from sin’s power in our lives. Paul proclaimed “ the full purpose of God”( Acts 20:27) All believers desperately need to hear the Full Gospel if they are to become truly spiritual and not just religious.", ImageName = "the-full-gospel.jpg", ImageUrl = "../../Images/Books/", DetailsPageUrl = "https://www.cfcindia.com/books/the-full-gospel" });
            books.Add(new BookDetails() { Title = "The Lord And His Church", Description = "The seven churches in Revelations.", ImageName = "the-lord-and-his-church.jpg", ImageUrl = "../../Images/Books/", DetailsPageUrl = "https://www.cfcindia.com/books/the-lord-and-his-church" });
            books.Add(new BookDetails() { Title = "The New Covenant Servant", Description = "Where are the prophets who can preach with the fire of the Holy Spirit who can preserve the purity of the Church. ..those who have overcome conscious sin, hate money and seek no man’s honour? God needs such men. If you want to be such a man , read this book….", ImageName = "the-new-covenant-servant.jpg", ImageUrl = "../../Images/Books/", DetailsPageUrl = "https://www.cfcindia.com/books/the-new-covenant-servant" });
            books.Add(new BookDetails() { Title = "The Purpose Of Failure", Description = "Do you see yourself as a “ hopeless failure”? Even if you have made a thousand new beginnings in the past and have failed , you can make a 1001st new beginning today. God can still fulfil His perfect plan for your life.", ImageName = "the-purpose-of-failure.jpg", ImageUrl = "../../Images/Books/", DetailsPageUrl = "https://www.cfcindia.com/books/the-purpose-of-failure" });
            books.Add(new BookDetails() { Title = "The Supreme Priorities", Description = "Like a two year old who prefers a cheap toy to a valuable cheque do you pursue after earthly rather than eternal things. What are your supreme priorities?", ImageName = "the-supreme-priorities.jpg", ImageUrl = "../../Images/Books/", DetailsPageUrl = "https://www.cfcindia.com/books/the-supreme-priorities" });
            books.Add(new BookDetails() { Title = "What The Lord Has Done For Me", Description = "A Testimony.", ImageName = "what-the-lord-has-done-for-me.jpg", ImageUrl = "../../Images/Books/", DetailsPageUrl = "https://www.cfcindia.com/books/what-the-lord-has-done-for-me" });
            books.Add(new BookDetails() { Title = "Woman, Why are you Weeping?", Description = "Comfort for suffering women.", ImageName = "woman-why-are-you-weeping.jpg", ImageUrl = "../../Images/Books/", DetailsPageUrl = "https://www.cfcindia.com/books/woman-why-are-you-weeping" });
            books.Add(new BookDetails() { Catagory = Catagory.Booklet, Title = "Fifty Marks Of Pharisees(Booklet)", Description = "A person can keep the commandments, be in pursuit of holiness or even be a missionary and still be in the danger of becoming a Pharisee. The very reason that the spirit of the Pharisee is...", ImageName = "FMPT.jpg", ImageUrl = "../../Images/Books/booklets/", DetailsPageUrl = "https://www.cfcindia.com/books/fifty-marks-of-phariseesbooklet" });
            books.Add(new BookDetails() { Catagory = Catagory.Booklet, Title = "Fifty Marks Of Godly Men (Booklet)", Description = "For believers – explaining what true godliness is.", ImageName = "FMGM.jpg", ImageUrl = "../../Images/Books/booklets/", DetailsPageUrl = "fifty-marks-of-godly-men-booklet" });
            books.Add(new BookDetails() { Catagory = Catagory.Booklet, Title = "Amazing Facts", Description = "An elementary book about God and man.", ImageName = "amazing-facts.jpg", ImageUrl = "../../Images/Books/booklets/", DetailsPageUrl = "https://www.cfcindia.com/books/amazing-facts" });
            books.Add(new BookDetails() { Catagory = Catagory.Booklet, Title = "The Real Truth", Description = "For those who know nothing about the Christian faith – explaining the message of salvation in detail – simply and clearly.", ImageName = "the-real-truth.jpg", ImageUrl = "../../Images/Books/booklets/", DetailsPageUrl = "https://www.cfcindia.com/books/the-real-truth" });

            return books;
        }

        public List<BookDetails> GetBooksLets()
        {
            List<BookDetails> books = new List<BookDetails>();

            books.Add(new BookDetails() { Catagory = Catagory.Booklet, Title = "Fifty Marks Of Pharisees(Booklet)", Description = "A person can keep the commandments, be in pursuit of holiness or even be a missionary and still be in the danger of becoming a Pharisee. The very reason that the spirit of the Pharisee is...", ImageName = "FMPT.jpg", ImageUrl = "../../Images/Books/booklets/", DetailsPageUrl = "https://www.cfcindia.com/books/fifty-marks-of-phariseesbooklet" });
            books.Add(new BookDetails() { Catagory = Catagory.Booklet, Title = "Fifty Marks Of Godly Men (Booklet)", Description = "For believers – explaining what true godliness is.", ImageName = "FMGM.jpg", ImageUrl = "../../Images/Books/booklets/", DetailsPageUrl = "fifty-marks-of-godly-men-booklet" });
            books.Add(new BookDetails() { Catagory = Catagory.Booklet, Title = "Amazing Facts", Description = "An elementary book about God and man.", ImageName = "amazing-facts.jpg", ImageUrl = "../../Images/Books/booklets/", DetailsPageUrl = "https://www.cfcindia.com/books/amazing-facts" });
            books.Add(new BookDetails() { Catagory = Catagory.Booklet, Title = "The Real Truth", Description = "For those who know nothing about the Christian faith – explaining the message of salvation in detail – simply and clearly.", ImageName = "the-real-truth.jpg", ImageUrl = "../../Images/Books/booklets/", DetailsPageUrl = "https://www.cfcindia.com/books/the-real-truth" });

            return books;
        }

        public List<BookDetails> GetTamilBooks()
        {
            List<BookDetails> books = new List<BookDetails>();

            books.Add(new BookDetails() { Title = "தேவ மனிதர்கள் எங்கே?", Description = "தேவா! காண அரிதாகிவிட்ட இந்நாட்களில்,\r\nமெய்யான தேவ மனிதர்களை எம் தேசத்தில் எழுப்புவீராக!\r\n", ImageName = "30-needed-men-of-god.jpg", ImageUrl = "../../Images/Books/bookstamil/", DetailsPageUrl = "https://tamil.cfcindia.com/ta/books/needed-men-of-god" });
            books.Add(new BookDetails() { Title = "நல்லதோர் குடும்பம்", Description = "தேவா! எமக்களித்த வாக்குத்தத்தம்: “பாலும் தேனும் ஓடும் மணவாழ்க்கையன்றோ!&#039;&#039;.", ImageName = "02-good-family.png", ImageUrl = "../../Images/Books/bookstamil/", DetailsPageUrl = "https://tamil.cfcindia.com/ta/books/a-good-family" });
            books.Add(new BookDetails() { Title = "நல்லதோர் அஸ்திபாரம்", Description = "“ஆழமாய் தோண்டி, அஸ்திவாரம் போட்டவன் வீடு ... அசைக்கப்படுவதில்லை” (லூக்கா 6:48).", ImageName = "01-good-foundation.png", ImageUrl = "../../Images/Books/bookstamil/", DetailsPageUrl = "https://tamil.cfcindia.com/ta/books/a-good-foundation" });
            books.Add(new BookDetails() { Title = "ஆவிக்குரிய தலைவன்", Description = "“நான் கிறிஸ்துவைப் பின்பற்றுவதுபோல நீங்களும் என்னைப் பின்பற்றுங்கள்” என உத்திரவாதமளிக்கும் தலைவர்கள் எழும்புவார்களாக!", ImageName = "03-a-spritual-leader.png", ImageUrl = "../../Images/Books/bookstamil/", DetailsPageUrl = "https://tamil.cfcindia.com/ta/books/a-spiritual-leader" });
            books.Add(new BookDetails() { Title = "சிலுவை இல்லாத இயேசுவா?", Description = "“சிலுவையில்லையேல்.... கிரீடமும் இல்லை!&#039;&#039; (NO CROSS?.... NO CROWN!)", ImageName = "04-crossless-jesus.png", ImageUrl = "../../Images/Books/bookstamil/", DetailsPageUrl = "https://tamil.cfcindia.com/ta/books/crossless-jesus" });
            books.Add(new BookDetails() { Title = "இன்று அவருடைய சத்தம்", Description = "“இன்று அவருடைய சத்தம் கேட்டு,.. அவருடைய இளைப்பாறுதல்&#039; வழி நடவுங்கள்&quot; (எபிரெயர் 3:7-10.)", ImageName = "05-daily-devotion.png", ImageUrl = "../../Images/Books/bookstamil/", DetailsPageUrl = "https://tamil.cfcindia.com/ta/books/daily-devotion" });
            books.Add(new BookDetails() { Title = "தாயின் பணியை தாங்கிடும் தேவன்!\r\n", Description = "&quot;உத்தம தாயின் பணிக்கு..... பரிசுத்தாவி துணையாளர். உதவி உண்டு!&quot; (யோவான் 14 : 18)", ImageName = "encouragement-for-mothers-tamil.jpg", ImageUrl = "../../Images/Books/bookstamil/", DetailsPageUrl = "https://tamil.cfcindia.com/ta/books/encouragement-for-mothers" });
            books.Add(new BookDetails() { Title = "தேவ சித்தம் அறியணுமே!", Description = "“உம்முடைய சித்தம் பரமண்டலத்திலே செய்யப்படுவதுபோல பூமியிலேயும் செய்யப்படுவதாக!” (மத்தேயு.6:10)", ImageName = "08-fnding-gods-will.png", ImageUrl = "../../Images/Books/bookstamil/", DetailsPageUrl = "https://tamil.cfcindia.com/ta/books/finding-gods-will" });
            books.Add(new BookDetails() { Title = "சோதனையில் தேவ அங்கீகாரம்", Description = "“உன்னை தேவனுக்கு முன்பாக உத்தமனாக நிறுத்தும்படி ஜாக்கிரதையாயிரு” (2தீமோத்தேயு 2:15).", ImageName = "09-gaininig-gods-approval.png", ImageUrl = "../../Images/Books/bookstamil/", DetailsPageUrl = "https://tamil.cfcindia.com/ta/books/gaining-gods-approval" });
            books.Add(new BookDetails() { Title = "தேவனை மையமாகக் கொண்டு ஜெபித்தல்", Description = "எம் ஜெபம் கேட்கப்படும்படி, தேவா! நீரே எம் வாழ்வின் மையமாகிட அருள் புரிவாய்!!", ImageName = "10-god-centered-praying.png", ImageUrl = "../../Images/Books/bookstamil/", DetailsPageUrl = "https://tamil.cfcindia.com/ta/books/god-centred-praying" });
            books.Add(new BookDetails() { Title = "தேவ ஊழியம் தேவ வழியில் செய்யப்படட்டும்", Description = "புதிய உடன்படிக்கை சபைகளின் தலைமைத்துவம்.", ImageName = "12-gods-work-done-in-gods-way.png", ImageUrl = "../../Images/Books/bookstamil/", DetailsPageUrl = "https://tamil.cfcindia.com/ta/books/god%E2%80%99s-work-done-in-god%E2%80%99s-way" });
            books.Add(new BookDetails() { Title = "சுபமங்கள தெய்வீக இல்லம்!", Description = "உங்கள் நாட்கள் பூமியின் மேல் பரலோகம் இருக்கும் நாட்களைப் போல நிச்சயமாய் இருக்கும் (உபாகமம் 11:18 - KJV).", ImageName = "13-heavenly-home.png", ImageUrl = "../../Images/Books/bookstamil/", DetailsPageUrl = "https://tamil.cfcindia.com/ta/books/heavenly-home" });
            books.Add(new BookDetails() { Title = "உங்கள் சத்துருவை அறிந்து கொள்ளுங்கள்", Description = "கெர்ச்சிக்கும் சிங்கம் போன்ற, ... சாத்தானால் மோசம்போகிட அவனுடைய தந்திரங்கள் நமக்குத் தெரியாதவைகள் அல்லவே!&quot; (1பேதுரு.5:8, 2கொரிந்தியர் 2:11)", ImageName = "14-know-your-enemey.png", ImageUrl = "../../Images/Books/bookstamil/", DetailsPageUrl = "https://tamil.cfcindia.com/ta/books/know-your-enemy" });
            books.Add(new BookDetails() { Title = "இயேசுவைப்போலவே வாழ்ந்திடலாம்", Description = "இயேசுவின் சாயலகத்தானே.... மறுரூபப்படுகிறோம்&quot; (2கொரிந்தியர் 3:18)", ImageName = "16-lving-as-jesus-lived.png", ImageUrl = "../../Images/Books/bookstamil/", DetailsPageUrl = "https://tamil.cfcindia.com/ta/books/living-as-jesus-lived" });
            books.Add(new BookDetails() { Title = "புதிய உடன்படிக்கை ஊழியன்", Description = "புதிய உடன்படிக்கையின் ஊழியக்காரராயிருக்கும்படி அவரே எங்களைத் தகுதியுள்ளவர்களாக்கினார்&quot; (2 கொரி 3:6)", ImageName = "18-new-covenant-servant.png", ImageUrl = "../../Images/Books/bookstamil/", DetailsPageUrl = "https://tamil.cfcindia.com/ta/books/new-covenant-servant" });
            books.Add(new BookDetails() { Title = "புது ரசம் புது துருத்தி", Description = "&quot;புது ரசமாம் உம் ஜீவனையும்.... அதைப் பாதுகாத்திட புது துருத்தியாம் உம் சபையையும் தந்திட்ட இயேசு தேவா நீர் வாழிய வாழியவே!!” (லூக்கா 5:38).", ImageName = "19-new-wine-new-skin.png", ImageUrl = "../../Images/Books/bookstamil/", DetailsPageUrl = "https://tamil.cfcindia.com/ta/books/new-wine-new-skin" });
            books.Add(new BookDetails() { Title = "மாயலோகம் விட்டு மோட்ச பயணம்", Description = "“முடிவுபரியந்தம் நிலை நிற்பவன் ‘மாத்திரமே&#039; இரட்சிக்கப்படுவான்!” (மத்தேயு 24:13)", ImageName = "20-pilgrm-progress.png", ImageUrl = "../../Images/Books/bookstamil/", DetailsPageUrl = "https://tamil.cfcindia.com/ta/books/pilgrim%E2%80%99s-progress" });
            books.Add(new BookDetails() { Title = "கர்த்தருக்கு ஊழியம் செய்திட உத்தம வழிகள்", Description = "“நான் எங்கே இருக்கிறேனோ அங்கே என் ஊழியக்காரனும் இருப்பான்” (யோவான் 12:26).", ImageName = "21-principles-of-serving-god.png", ImageUrl = "../../Images/Books/bookstamil/", DetailsPageUrl = "https://tamil.cfcindia.com/ta/books/principles-of-serving-god" });
            books.Add(new BookDetails() { Title = "படுதோல்வியில் பரம நோக்கம்", Description = "மீறுதலை மன்னிக்கிற தேவரீருக்கு ஒப்பான தேவன் யார்? அவர் திரும்ப நம்மேல் இரங்குவார்!” (மீகா 7:18,19)", ImageName = "22-purpose-of-failure.png", ImageUrl = "../../Images/Books/bookstamil/", DetailsPageUrl = "https://tamil.cfcindia.com/ta/books/purpose-of-failure" });
            books.Add(new BookDetails() { Title = "வெற்றியின் இரகசியங்கள்", Description = "“கிறிஸ்துவுக்குள் எங்களை எப்பொழுதும் வெற்றி சிறக்கப்பண்ணும்...... தேவனுக்கு ஸ்தோத்திரம்” (2 கொரி 2:14).", ImageName = "23-secrets-of-victory.png", ImageUrl = "../../Images/Books/bookstamil/", DetailsPageUrl = "https://tamil.cfcindia.com/ta/books/secrets-of-victory" });
            books.Add(new BookDetails() { Title = "பாலிய ஈர்ப்பும் திருமணமும்", Description = "“தேவன் மனுஷனை ஆணும் பெண்ணுமாக சிருஷ்டித்தார்..... ஒருவருக்கொருவர் ஏற்ற துணையை தேவன் உண்டாக்குகிறார்” (ஆதி 1:27; 2:18).", ImageName = "24-sex-love-and-marriage.png", ImageUrl = "../../Images/Books/bookstamil/", DetailsPageUrl = "https://tamil.cfcindia.com/ta/books/sex-love-marriage" });
            books.Add(new BookDetails() { Title = "ஆராதனை கூடுகை ஜன சங்கம் ஸ்தல சபை\r\n", Description = "“இரு திசை கொண்ட சிலுவையின் உறவே, புதிய உடன்படிக்கையின் சபையை கட்டும்!&quot;", ImageName = "25-the-congregation-the-club-and-the-church.png", ImageUrl = "../../Images/Books/bookstamil/", DetailsPageUrl = "https://tamil.cfcindia.com/ta/books/the-congregation-the-club-and-the-church" });
            books.Add(new BookDetails() { Title = "யார், பின்பற்ற உகந்த பிரசங்கி?\r\n", Description = "நான் கிறிஸ்துவை பின்பற்றுகிறது போல நீங்கள் என்னை பின்பற்றுங்கள் (1கொரி 11:1)", ImageName = "26-the-preacher-whom-i-want-to-follow.png", ImageUrl = "../../Images/Books/bookstamil/", DetailsPageUrl = "https://tamil.cfcindia.com/ta/books/the-preacher-whom-i-want-to-follow" });
            books.Add(new BookDetails() { Title = "நீங்கள் எப்படியிருக்க தேவன் விரும்புகிறார்?", Description = "“என் இருதயத்துக்கு ஏற்றவனாகக் கண்டேன்” (அப்போஸ்தலர் 13:22)", ImageName = "28-what-god-wants-you-to-be.png", ImageUrl = "../../Images/Books/bookstamil/", DetailsPageUrl = "https://tamil.cfcindia.com/ta/books/what-god-wants-you-to-be" });
            books.Add(new BookDetails() { Title = "முத்துக் குவியல்", Description = "“பரலோக ராஜ்யம் நல்ல முத்துக்களைத் தேடுகிற வியாபாரிக்கு\r\nஒப்பாயிருக்கிறது ” (மத்தேயு.13:45)", ImageName = "17-muthukuvial.png", ImageUrl = "../../Images/Books/bookstamil/", DetailsPageUrl = "https://tamil.cfcindia.com/ta/books/nuggets-of-pearls" });
            books.Add(new BookDetails() { Title = "தேவ மனிதரின் \"50\" அடையாளங்கள் (சிற்றேடு)", Description = "", ImageName = "FMGM.jpg", ImageUrl = "../../Images/Books/bookstamil/", DetailsPageUrl = "https://tamil.cfcindia.com/ta/books/fifty-marks-of-godly-men-booklet" });
            books.Add(new BookDetails() { Title = "பரிசேயரின் “50” அடையாளங்கள் (சிற்றேடு) ", Description = "", ImageName = "fifty-marks-of-phariseesbooklet.jpg", ImageUrl = "../../Images/Books/bookstamil/", DetailsPageUrl = "https://tamil.cfcindia.com/ta/books/fifty-marks-of-phariseesbooklet" });
            books.Add(new BookDetails() { Title = "வியப்பூட்டும் உண்மைகள் (சிற்றேடு)", Description = "தேவனையும் மனிதனையும் குறித்ததான அடிப்படை காரியங்கள்", ImageName = "amazing-facts.jpg", ImageUrl = "../../Images/Books/bookstamil/", DetailsPageUrl = "https://tamil.cfcindia.com/ta/books/amazing-facts-booklet" });
            books.Add(new BookDetails() { Title = "இதுவே மெய்யான சத்தியம் (சிற்றேடு)", Description = "கிறிஸ்துவத்தை பற்றி அறியாதவர்களுக்கு, எளிமையான முறையில் இரட்சிப்பைக் குறித்த விளக்கம்", ImageName = "the-real-truth.jpg", ImageUrl = "../../Images/Books/bookstamil/", DetailsPageUrl = "https://tamil.cfcindia.com/ta/books/the-real-truth-booklet" });


            return books;
        }


    }
    }